baseurl      = "https://hugomoraga.github.io/hugo-tailwind-boilerplate/"
title        = "hugo-tailwind-boilerplate"
languageCode = "es-ES"
publishDir = "docs"

[[menu.sidebar]]
name = "Home"
url = "/"
weight = 1

[[menu.sidebar]]
name = "Articles"
url = "/articles"
weight = 2